version: 2.1
orbs:
  snyk: snyk/snyk@0.0.13
jobs:
  build-app:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - app-dependencies-{{ checksum "package-lock.json" }}
            - app-dependencies-
      - run:
          name: install dependencies
          command: |
            npm install --no-audit
            npm build
      - save_cache:
          paths:
            - ./node_modules
            - ./.next
          key: app-dependencies-{{ checksum "package-lock.json" }}
  audit:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - app-dependencies-{{ checksum "package-lock.json" }}
            - app-dependencies-
      - run:
          name: npm audit
          command: |
            npm audit
  lint:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - app-dependencies-{{ checksum "package-lock.json" }}
            - app-dependencies-
      - run:
          name: run lint
          command: |
            npm run lint

  unit:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - app-dependencies-{{ checksum "package-lock.json" }}
            - app-dependencies-
      - run:
          name: npm audit
          command: |
            npm run unit
  build-image:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          command: |
            IMAGE=0.1.$CIRCLE_BUILD_NUM
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV
            echo 'export $IMAGE' >> $BASH_ENV && source $BASH_ENV
            docker build -t $IMAGE .
            docker save --output image.tar $IMAGE
      - snyk/scan:
          fail-on-issues: true
          monitor-on-build: true
          docker-image-name: $IMAGE
          target-file: "Dockerfile"
          project: ${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}-app
          token-variable: SNYK_TOKEN
          additional-arguments: --exclude-base-image-vulns
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  snyk-scan:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - restore_cache:
          keys:
            - app-dependencies-{{ checksum "package-lock.json" }}
            - app-dependencies-
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: install snyk
          command: |
            npm install snyk --no-audit
            ./node_modules/.bin/snyk config set api=${SNYK_TOKEN}
      - run:
          name: snyk security scan
          command: |
            ./node_modules/.bin/snyk container test 0.1.$CIRCLE_BUILD_NUM --file=Dockerfile --exclude-base-image-vulns
workflows:
  build:
    jobs:
#      - build-app
#      - audit:
#          requires: [build-app]
#      - lint:
#          requires: [build-app]
#      - unit:
#          requires: [build-app]
#      - build-image:
#          requires: [audit, lint, unit]
      - build-image
#      - snyk-scan:
#          requires: [build-image]


#            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
#            docker push $DOCKER_REPO:$TAG
#      - run:
#          name: archive docker image
#          command: |
#            docker save --output image.tar $TAG:latest